export type CategoryId = "university" | "pbsa" | "su" | "private";

export type Listing = {
  id: string;
  category: CategoryId;
  name: string;
  type: string;
  area: string;
  walk: string;
  price: string;
  sourceUrl: string;
  sourceLabel: string;
  origin: string;
  note: string;
  priority: 3 | 4 | 5;
  tags: string[];
  topPick?: boolean;
  verifyLive?: boolean;
  map: {
    x: number;
    y: number;
  };
};

export const categories: Record<CategoryId, { label: string; short: string }> = {
  university: { label: "大学官方", short: "University" },
  pbsa: { label: "学生公寓", short: "PBSA" },
  su: { label: "Bristol SU Lettings", short: "SU" },
  private: { label: "普通社会房源", short: "Private" },
};

export const destination = {
  name: "University of Bristol Law School / Wills Memorial Building",
  address: "Wills Memorial Building, Queens Road, Bristol BS8 1RJ",
  sourceUrl:
    "https://www.bristol.ac.uk/directory/learning-facilities/central-teaching-spaces/wills-memorial-building/",
  map: { x: 41, y: 41 },
};

export const verificationLinks = [
  {
    label: "Wills Memorial Building official address",
    url: destination.sourceUrl,
  },
  {
    label: "University accommodation 2026/27 costs",
    url: "https://www.bristol.ac.uk/accommodation/about/costs/cost-by-residence/",
  },
  {
    label: "Bristol private renting: guarantor and right to rent",
    url: "https://www.bristol.ac.uk/accommodation/privately-rented/finding-private-accommodation/tenancies-and-terms/",
  },
  {
    label: "Bristol private renting: costs, bills, deposits",
    url: "https://www.bristol.ac.uk/accommodation/privately-rented/finding-private-accommodation/private-renting-costs/",
  },
  {
    label: "Bristol SU Lettings",
    url: "https://www.bristolsulettings.co.uk/",
  },
];

export function appleMapsUrl(origin: string) {
  const params = new URLSearchParams({
    saddr: origin,
    daddr: destination.address,
    dirflg: "w",
  });
  return `https://maps.apple.com/?${params.toString()}`;
}

export function googleMapsUrl(origin: string) {
  const params = new URLSearchParams({
    api: "1",
    origin,
    destination: destination.address,
    travelmode: "walking",
  });
  return `https://www.google.com/maps/dir/?${params.toString()}`;
}

export const listings: Listing[] = [
  {
    id: "marlborough-house",
    category: "university",
    name: "Marlborough House",
    type: "Postgraduate serviced studio",
    area: "BS1 3NX",
    walk: "约 20 分钟",
    price: "£339.50/w, 51 周, 总 £17,314.50",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/marlborough-house/",
    sourceLabel: "University of Bristol",
    origin: "Marlborough Street, Bristol BS1 3NX",
    note: "PG、官方、服务型，含清洁/床品/厨房设备；但 studio 只有少量房间，通常很难抢。",
    priority: 5,
    tags: ["官方", "PG", "服务型", "稀缺"],
    topPick: true,
    map: { x: 58, y: 33 },
  },
  {
    id: "orchard-heights",
    category: "university",
    name: "Orchard Heights",
    type: "Postgraduate studio",
    area: "BS1 5BY",
    walk: "约 15 分钟",
    price: "£336/w, 51 周, 总 £17,136",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/orchard-heights/",
    sourceLabel: "University of Bristol",
    origin: "31 Frogmore Street, Bristol BS1 5BY",
    note: "官方 PG studio，价格比很多私营 PBSA 稳；市中心晚上会比 Clifton 热闹。",
    priority: 5,
    tags: ["官方", "PG", "市中心"],
    map: { x: 51, y: 54 },
  },
  {
    id: "the-courtrooms",
    category: "university",
    name: "The Courtrooms",
    type: "Postgraduate studio",
    area: "BS1 2AF",
    walk: "约 14 分钟",
    price: "£332.50/w, 51 周, 总 £16,957.50",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/the-courtrooms/",
    sourceLabel: "University of Bristol",
    origin: "Rupert Street, Bristol BS1 2AF",
    note: "位置和价格都不错，更 city-centre；噪音和街区感需要接受。",
    priority: 4,
    tags: ["官方", "PG", "市中心"],
    map: { x: 54, y: 43 },
  },
  {
    id: "campus-houses",
    category: "university",
    name: "Campus Houses",
    type: "1-bed flat, 多为 couple/family",
    area: "BS2 8BW",
    walk: "约 5 分钟",
    price: "£322/w, 51 周, 总 £16,422",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/houses/",
    sourceLabel: "University of Bristol",
    origin: "St Michael's Park, Bristol BS2 8BW",
    note: "位置极好、官方、价格好；但官网定位偏 couple/family，单人 LLM 不一定能申请。",
    priority: 4,
    tags: ["官方", "近学校", "需确认资格"],
    map: { x: 47, y: 35 },
  },
  {
    id: "manor-hall",
    category: "university",
    name: "Manor Hall",
    type: "1-bed flat, 多为 couple/family",
    area: "BS8 1BU",
    walk: "约 15 分钟",
    price: "£308/w, 51 周, 总 £15,708",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/manor/",
    sourceLabel: "University of Bristol",
    origin: "Lower Clifton Hill, Bristol BS8 1BU",
    note: "Clifton 位置好，价格很香；但偏 couple/family，且楼体较老。",
    priority: 3,
    tags: ["官方", "Clifton", "低价"],
    map: { x: 30, y: 45 },
  },
  {
    id: "college-house",
    category: "pbsa",
    name: "College House",
    type: "Studios, 偏 PG 友好",
    area: "BS1 5SP",
    walk: "约 5-8 分钟",
    price: "2026/27 from £386/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/college-house",
    sourceLabel: "Hello Student",
    origin: "32-36 College Green, Bristol BS1 5SP",
    note: "安静、独立、全包、近学校，适合想省心的 LLM；预算会高一些。",
    priority: 5,
    tags: ["全包", "PG 友好", "近学校"],
    topPick: true,
    map: { x: 43, y: 49 },
  },
  {
    id: "st-marys",
    category: "pbsa",
    name: "St Mary's",
    type: "Studios / 1-bed / 2-bed apartments",
    area: "BS8 1JU",
    walk: "约 9 分钟",
    price: "官网实时 View prices",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/st-marys",
    sourceLabel: "Hello Student",
    origin: "Upper Byron Place, Bristol BS8 1JU",
    note: "Clifton Triangle 地段非常好，官方页面确认 studios、1/2-bed apartments 和 all-inclusive bills。",
    priority: 5,
    tags: ["Clifton", "全包", "高预算"],
    map: { x: 34, y: 38 },
  },
  {
    id: "quarter-house",
    category: "pbsa",
    name: "The Quarter House",
    type: "Studios",
    area: "BS1 3NX",
    walk: "约 14-20 分钟",
    price: "Studio £340-405/w",
    sourceUrl: "https://prestigestudentliving.com/student-accommodation/bristol/the-quarter-house",
    sourceLabel: "Prestige Student Living",
    origin: "17 Marlborough Street, Bristol BS1 3NX",
    note: "新、设施强、价格相对合理；No Place / No Visa, No Pay 对国际学生友好。",
    priority: 5,
    tags: ["新", "No Visa No Pay", "设施强"],
    topPick: true,
    map: { x: 57, y: 34 },
  },
  {
    id: "market-quarter",
    category: "pbsa",
    name: "Market Quarter Studios",
    type: "Studios",
    area: "BS1 1BT",
    walk: "约 12-15 分钟",
    price: "2026/27 from £338/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/market-quarter",
    sourceLabel: "Hello Student",
    origin: "13-21 Baldwin Street, Bristol BS1 1BT",
    note: "市中心 studio，生活方便，全包；Baldwin Street 周边晚上较热闹。",
    priority: 4,
    tags: ["市中心", "全包"],
    map: { x: 54, y: 55 },
  },
  {
    id: "college-green",
    category: "pbsa",
    name: "College Green",
    type: "Studios / shared apartments",
    area: "BS1 5SH",
    walk: "约 7-10 分钟",
    price: "from £293/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/college-green",
    sourceLabel: "Hello Student",
    origin: "39-43 College Green, Bristol BS1 5SH",
    note: "离 Wills 很近，价格可能比 College House / St Mary's 更友好。",
    priority: 4,
    tags: ["近学校", "预算友好"],
    map: { x: 44, y: 50 },
  },
  {
    id: "iq-bristol",
    category: "pbsa",
    name: "iQ Bristol",
    type: "Studios / ensuite",
    area: "BS1 3EQ",
    walk: "约 15-20 分钟",
    price: "from £315/w, studio 需实时查",
    sourceUrl: "https://www.iqstudentaccommodation.com/bristol/iq-bristol",
    sourceLabel: "iQ Student Accommodation",
    origin: "Marlborough Street, Bristol BS1 3EQ",
    note: "国际学生流程成熟；guarantor、No Visa No Pay 等条款需以官网实时房型为准。",
    priority: 4,
    tags: ["国际学生", "市中心"],
    map: { x: 59, y: 36 },
  },
  {
    id: "new-bridewell",
    category: "pbsa",
    name: "New Bridewell",
    type: "Studios",
    area: "BS1 2BA",
    walk: "约 10-15 分钟",
    price: "Bronze £390/w, higher tiers around £460/w",
    sourceUrl: "https://www.thisisfresh.com/bristol/new-bridewell",
    sourceLabel: "Fresh",
    origin: "Nelson Street, Bristol BS1 2BA",
    note: "Fresh 系列，位置近，设施稳；市中心噪音和治安体感要看房间朝向。",
    priority: 4,
    tags: ["市中心", "高预算"],
    map: { x: 56, y: 49 },
  },
  {
    id: "tower-bristol",
    category: "pbsa",
    name: "Tower Bristol",
    type: "Studios, 部分可 dual occupancy",
    area: "BS1 2QJ",
    walk: "约 10-15 分钟",
    price: "Bronze Studio £360/w, Platinum £421/w",
    sourceUrl: "https://www.collegiate-ac.com/uk-student-accommodation/bristol/tower/",
    sourceLabel: "Collegiate",
    origin: "Rupert Street, Bristol BS1 2QJ",
    note: "性价比不错；部分房型可能 non-opening windows，必须问通风和朝向。",
    priority: 4,
    tags: ["市中心", "需问通风"],
    map: { x: 55, y: 45 },
  },
  {
    id: "st-lawrence-house",
    category: "pbsa",
    name: "St Lawrence House",
    type: "Studios",
    area: "BS1 2HF",
    walk: "约 15-18 分钟",
    price: "£399-465/w",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/st-lawrence-house",
    sourceLabel: "Homes for Students",
    origin: "29-31 Broad Street, Bristol BS1 2HF",
    note: "部分 studio 带洗烘机是加分项；Broad Street 去学校不远但夜间城市感强。",
    priority: 4,
    tags: ["市中心", "带洗烘"],
    map: { x: 60, y: 51 },
  },
  {
    id: "king-square-studios",
    category: "pbsa",
    name: "King Square Studios",
    type: "Studios / 1-bed apartment",
    area: "BS2 8AU",
    walk: "约 16-20 分钟",
    price: "Studio from £295-299/w; 1-bed from £475/w",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/king-square-studios",
    sourceLabel: "Homes for Students",
    origin: "4 Dighton Street, Bristol BS2 8AU",
    note: "价格相对低，但接近 20 分钟边界；适合预算敏感又想独立居住的人。",
    priority: 3,
    tags: ["预算友好", "20 分钟边界"],
    map: { x: 65, y: 35 },
  },
  {
    id: "queens-road-44a",
    category: "su",
    name: "44a Queens Road",
    type: "Mezzanine studio",
    area: "BS8 1FG",
    walk: "约 2-5 分钟",
    price: "£1,500 pcm, all bills",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/3157-44a-queens-road-clifton-bristol",
    sourceLabel: "Bristol SU Lettings",
    origin: "44a Queens Road, Clifton, Bristol BS8 1FG",
    note: "离法学院极近，all bills + super-fast Wi-Fi；贵，但地段基本无敌。",
    priority: 5,
    tags: ["SU", "全包", "最近"],
    topPick: true,
    map: { x: 39, y: 40 },
  },
  {
    id: "park-street-1bed",
    category: "su",
    name: "Park Street 1-bed",
    type: "1-bed student flat",
    area: "BS1",
    walk: "约 5 分钟",
    price: "£440/w, bills/Wi-Fi/insurance included",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/3026-park-street-bristol",
    sourceLabel: "Bristol SU Lettings",
    origin: "Park Street, Bristol",
    note: "真正 1B1B，位置近、学生合同、全包；Park Street 晚上可能吵。",
    priority: 5,
    tags: ["SU", "1B1B", "全包"],
    topPick: true,
    map: { x: 42, y: 46 },
  },
  {
    id: "manor-house-park-lane",
    category: "su",
    name: "The Manor House, Park Lane",
    type: "1-bed ensuite student flat",
    area: "BS1/BS8",
    walk: "约 5-8 分钟",
    price: "£560/w, all bills",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/370-the-manor-house-park-lane-bristol",
    sourceLabel: "Bristol SU Lettings",
    origin: "The Manor House, Park Lane, Bristol",
    note: "很高配、在 UoB precinct，适合预算高的人。",
    priority: 5,
    tags: ["SU", "高配", "高预算"],
    map: { x: 39, y: 47 },
  },
  {
    id: "park-street-studio",
    category: "su",
    name: "Park Street studio",
    type: "Studio",
    area: "BS1 5JG",
    walk: "约 5 分钟",
    price: "£305/w, bills/Wi-Fi included",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/2995-park-street-bristol",
    sourceLabel: "Bristol SU Lettings",
    origin: "34 Park Street, Bristol BS1 5JG",
    note: "性价比很高，适合单人 LLM；重点看面积、采光和噪音。",
    priority: 4,
    tags: ["SU", "预算友好", "全包"],
    map: { x: 41, y: 45 },
  },
  {
    id: "park-row",
    category: "su",
    name: "Park Row",
    type: "1-bed flat",
    area: "BS1",
    walk: "约 5-8 分钟",
    price: "£1,300 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/2862-park-row-bristol",
    sourceLabel: "Bristol SU Lettings",
    origin: "Park Row, Bristol",
    note: "更像正常住家的 1B1B；2026/27 可租情况需邮件确认。",
    priority: 4,
    tags: ["SU", "1B1B", "需确认"],
    map: { x: 47, y: 39 },
  },
  {
    id: "dover-place",
    category: "su",
    name: "Dover Place",
    type: "1-bed flat",
    area: "Clifton / Triangle",
    walk: "约 3-6 分钟",
    price: "£1,350 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/search-results?start=72",
    sourceLabel: "Bristol SU search",
    origin: "Dover Place, Bristol",
    note: "位置在 SU / Clifton Triangle 旁，适合研究生；bills 是否 included 要确认。",
    priority: 4,
    tags: ["SU", "Clifton", "1B1B"],
    map: { x: 36, y: 42 },
  },
  {
    id: "cotham-road-south",
    category: "su",
    name: "Cotham Road South",
    type: "Studio",
    area: "BS6/BS8",
    walk: "约 5-10 分钟",
    price: "£1,150 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/search-results?start=72",
    sourceLabel: "Bristol SU search",
    origin: "Cotham Road South, Bristol",
    note: "私人小院 studio，位置好，价格比 PBSA 温和；bills 要确认。",
    priority: 4,
    tags: ["SU", "预算友好", "需问 bills"],
    map: { x: 42, y: 28 },
  },
  {
    id: "whiteladies-road",
    category: "su",
    name: "Whiteladies Road",
    type: "Studio",
    area: "BS8",
    walk: "约 10-15 分钟",
    price: "£1,500 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let?start=72",
    sourceLabel: "Bristol SU search",
    origin: "Whiteladies Road, Bristol BS8",
    note: "生活方便，Clifton / Redland 氛围好；价格偏高。",
    priority: 3,
    tags: ["SU", "Clifton", "高预算"],
    map: { x: 25, y: 25 },
  },
  {
    id: "st-stephens-street",
    category: "su",
    name: "14 St Stephens Street",
    type: "Studio",
    area: "BS1",
    walk: "约 12-17 分钟",
    price: "£1,150 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let?start=84",
    sourceLabel: "Bristol SU search",
    origin: "14 St Stephens Street, Bristol",
    note: "市中心、价格还行；晚上环境不如 Clifton 安静。",
    priority: 3,
    tags: ["SU", "市中心", "预算友好"],
    map: { x: 57, y: 58 },
  },
  {
    id: "private-queens-road",
    category: "private",
    name: "Queens Road, Clifton",
    type: "Studio / 1-bed student studio",
    area: "BS8",
    walk: "约 3-5 分钟",
    price: "约 £1,250 pcm / £288 pw",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/studio-flats.html",
    sourceLabel: "Rightmove BS8 studios",
    origin: "Queens Road, Clifton, Bristol BS8",
    note: "对 Law School 最方便；主路/酒吧噪音和房间大小要重点看。",
    priority: 5,
    tags: ["最近", "社会房源", "预算友好"],
    verifyLive: true,
    map: { x: 38, y: 40 },
  },
  {
    id: "berkeley-square",
    category: "private",
    name: "Berkeley Square",
    type: "Studio / 1-bed",
    area: "BS8",
    walk: "约 3-6 分钟",
    price: "Studio £1,175 pcm; 1-bed £1,495 pcm",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/studio-flats.html",
    sourceLabel: "Rightmove BS8 studios",
    origin: "Berkeley Square, Bristol",
    note: "位置顶级，靠近 Wills 和 Park Street；社会房合同细节要更仔细。",
    priority: 4,
    tags: ["Clifton", "近学校"],
    verifyLive: true,
    map: { x: 35, y: 46 },
  },
  {
    id: "jacobs-wells-road",
    category: "private",
    name: "Jacobs Wells Road",
    type: "Student-only studios",
    area: "BS8",
    walk: "约 8-12 分钟",
    price: "£1,265 pcm / £292 pw, all bills",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/studio-flats.html",
    sourceLabel: "Rightmove student studios",
    origin: "Jacobs Wells Road, Bristol BS8",
    note: "到 Clifton Triangle 很近，全包省心；注意坡度、采光和隔音。",
    priority: 4,
    tags: ["全包", "学生房", "近学校"],
    verifyLive: true,
    map: { x: 31, y: 54 },
  },
  {
    id: "sutherland-place",
    category: "private",
    name: "Sutherland Place",
    type: "1-bed flat",
    area: "BS8",
    walk: "约 10-15 分钟",
    price: "£1,350 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    origin: "Sutherland Place, Bristol BS8",
    note: "Clifton 住宅感强，离 Whiteladies Road 近；合同、家具、bills 要问清楚。",
    priority: 4,
    tags: ["Clifton", "1B1B"],
    verifyLive: true,
    map: { x: 18, y: 34 },
  },
  {
    id: "meridian-place",
    category: "private",
    name: "Meridian Place",
    type: "1-bed flat",
    area: "Clifton BS8",
    walk: "约 8-12 分钟",
    price: "£1,400 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    origin: "Meridian Place, Clifton, Bristol BS8",
    note: "Clifton 好位置，社会房源里比较稳；问家具、bills、guarantor。",
    priority: 4,
    tags: ["Clifton", "1B1B"],
    verifyLive: true,
    map: { x: 24, y: 42 },
  },
  {
    id: "baldwin-street",
    category: "private",
    name: "Baldwin Street",
    type: "Studio",
    area: "BS1",
    walk: "约 12-15 分钟",
    price: "£1,350-1,475 pcm",
    sourceUrl:
      "https://www.bristolpropertycentre.co.uk/property-details/a05537d2-dee7-4685-a4c1-6294071ea4a9/bristol-city/bristol/baldwin-chambers-baldwin-street-1",
    sourceLabel: "Bristol Property Centre",
    origin: "Baldwin Street, Bristol BS1",
    note: "市中心生活方便，价格中等；晚上热闹，适合能接受 city-centre 的人。",
    priority: 4,
    tags: ["市中心", "Studio"],
    verifyLive: true,
    map: { x: 55, y: 56 },
  },
  {
    id: "queen-square",
    category: "private",
    name: "Queen Square",
    type: "Student studios",
    area: "BS1",
    walk: "约 17-20 分钟",
    price: "£1,170-1,404 pcm",
    sourceUrl: "https://www.zoopla.co.uk/to-rent/flats/bristol/queen-square/",
    sourceLabel: "Zoopla Queen Square",
    origin: "Queen Square, Bristol BS1",
    note: "位置漂亮、靠近 Harbourside；到 Wills 卡 20 分钟边界。",
    priority: 3,
    tags: ["Harbourside", "20 分钟边界"],
    verifyLive: true,
    map: { x: 55, y: 68 },
  },
  {
    id: "canynge-square",
    category: "private",
    name: "Canynge Square",
    type: "1-bed flat",
    area: "Clifton BS8",
    walk: "约 16-20 分钟",
    price: "£1,300 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    origin: "Canynge Square, Clifton, Bristol BS8",
    note: "Clifton Village 生活品质高；去 Wills 有坡，时间接近 20 分钟。",
    priority: 3,
    tags: ["Clifton Village", "1B1B"],
    verifyLive: true,
    map: { x: 13, y: 56 },
  },
  {
    id: "clifton-park-road",
    category: "private",
    name: "Clifton Park Road",
    type: "1-bed flat",
    area: "BS8",
    walk: "约 12-18 分钟",
    price: "£1,600 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    origin: "Clifton Park Road, Bristol BS8",
    note: "居住感强，位置好；价格偏高。",
    priority: 3,
    tags: ["Clifton", "高预算"],
    verifyLive: true,
    map: { x: 16, y: 49 },
  },
  {
    id: "kings-parade-avenue",
    category: "private",
    name: "Kings Parade Avenue",
    type: "Studio",
    area: "Whiteladies 附近",
    walk: "约 15-20 分钟",
    price: "约 £950 pcm",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/flats.html",
    sourceLabel: "Rightmove BS8 flats",
    origin: "Kings Parade Avenue, Bristol BS8",
    note: "价格低，但要重点检查面积、采光、潮湿、取暖和 bills。",
    priority: 3,
    tags: ["低价", "需仔细看房"],
    verifyLive: true,
    map: { x: 19, y: 24 },
  },
];
