export type CategoryId = "university" | "pbsa" | "su" | "private";
export type SourceStatus = "verified" | "provider" | "search" | "volatile";

export type Listing = {
  id: string;
  category: CategoryId;
  name: string;
  type: string;
  area: string;
  walk: string;
  walkMinutes: number;
  price: string;
  sourceUrl: string;
  sourceLabel: string;
  sourceStatus: SourceStatus;
  sourceGroup: string;
  origin: string;
  note: string;
  priority: 3 | 4 | 5;
  tags: string[];
  topPick?: boolean;
  verifyLive?: boolean;
  borderline?: boolean;
  lat: number;
  lng: number;
};

export type SourceAudit = {
  group: string;
  included: string[];
  borderline: string[];
  excluded: string[];
};

export type ApplicationLink = {
  label: string;
  url: string;
  note: string;
};

export const categories: Record<CategoryId, { label: string; short: string }> = {
  university: { label: "大学官方", short: "University" },
  pbsa: { label: "学生公寓", short: "PBSA" },
  su: { label: "Bristol SU Lettings", short: "SU" },
  private: { label: "普通社会房源", short: "Private" },
};

export const destination = {
  name: "University of Bristol Law School / Wills Memorial Building",
  address: "Wills Memorial Building, Queens Road, Bristol BS8 1RJ",
  sourceUrl:
    "https://www.bristol.ac.uk/directory/learning-facilities/central-teaching-spaces/wills-memorial-building/",
  lat: 51.4563553,
  lng: -2.604566,
};

export const verificationLinks = [
  {
    label: "Wills Memorial Building official address",
    url: destination.sourceUrl,
  },
  {
    label: "University accommodation 2026/27 costs",
    url: "https://www.bristol.ac.uk/accommodation/about/costs/cost-by-residence/",
  },
  {
    label: "Apply for University accommodation",
    url: "https://www.bristol.ac.uk/accommodation/apply/",
  },
  {
    label: "Accommodation Portal",
    url: "https://bristol.starrezhousing.com/",
  },
  {
    label: "University PBSA provider list",
    url: "https://www.bristol.ac.uk/accommodation/privately-rented/finding-private-accommodation/finding-properties-to-view/pbsa/",
  },
  {
    label: "Bristol private renting: guarantor and right to rent",
    url: "https://www.bristol.ac.uk/accommodation/privately-rented/finding-private-accommodation/tenancies-and-terms/",
  },
  {
    label: "Bristol SU Lettings",
    url: "https://www.bristolsulettings.co.uk/",
  },
  {
    label: "OpenStreetMap data attribution",
    url: "https://www.openstreetmap.org/copyright",
  },
];

export function appleMapsUrl(origin: string) {
  const params = new URLSearchParams({
    saddr: origin,
    daddr: destination.address,
    dirflg: "w",
  });
  return `https://maps.apple.com/?${params.toString()}`;
}

export function googleMapsUrl(origin: string) {
  const params = new URLSearchParams({
    api: "1",
    origin,
    destination: destination.address,
    travelmode: "walking",
  });
  return `https://www.google.com/maps/dir/?${params.toString()}`;
}

const officialCostTable =
  "https://www.bristol.ac.uk/accommodation/about/costs/cost-by-residence/";

export const applicationLinks: ApplicationLink[] = [
  {
    label: "Apply overview",
    url: "https://www.bristol.ac.uk/accommodation/apply/",
    note: "官方住宿申请总入口：先看 guarantee、key dates、terms，再进 portal。",
  },
  {
    label: "Accommodation Portal",
    url: "https://bristol.starrezhousing.com/",
    note: "注册并填写住宿申请；之后也在这里查看/接受 offer。",
  },
  {
    label: "How to apply",
    url: "https://www.bristol.ac.uk/accommodation/apply/how-to-apply/",
    note: "官方说明：需要 University of Bristol student number，并在 portal 里填写申请表。",
  },
  {
    label: "Key dates",
    url: "https://www.bristol.ac.uk/accommodation/apply/key-dates/",
    note: "2026 入学：4 月 8 日开放申请；6 月 30 日前申请才满足 guarantee deadline。",
  },
  {
    label: "Guarantee",
    url: "https://www.bristol.ac.uk/accommodation/apply/guarantee/",
    note: "海外费率、第一年、new full-time postgraduate、unaccompanied/single 等条件很关键。",
  },
  {
    label: "Portal help",
    url: "https://www.bristol.ac.uk/accommodation/contact/portal/",
    note: "Portal 注册/登录/激活邮件问题；官方联系邮箱 student-accommodation@bristol.ac.uk。",
  },
];

export const listings: Listing[] = [
  {
    id: "marlborough-house",
    category: "university",
    name: "Marlborough House",
    type: "Postgraduate serviced studio",
    area: "BS1 3NX",
    walk: "约 20 分钟",
    walkMinutes: 20,
    price: "£339.50/w, 51 周, 总 £17,314.50",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/marlborough-house/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Marlborough Street, Bristol BS1 3NX",
    note: "PG、官方、服务型，含清洁/床品/厨房设备；但 serviced studio 只有 3 间，极难抢。",
    priority: 5,
    tags: ["官方", "PG", "服务型", "稀缺"],
    topPick: true,
    lat: 51.4601339,
    lng: -2.5923025,
  },
  {
    id: "orchard-heights",
    category: "university",
    name: "Orchard Heights",
    type: "Postgraduate studio",
    area: "BS1 5BY",
    walk: "约 15 分钟",
    walkMinutes: 15,
    price: "£336/w, 51 周, 总 £17,136",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/orchard-heights/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "31 Frogmore Street, Bristol BS1 5BY",
    note: "官方 PG studio，价格比很多私营 PBSA 稳；Frogmore / 市中心晚上会比 Clifton 热闹。",
    priority: 5,
    tags: ["官方", "PG", "市中心"],
    lat: 51.4546196,
    lng: -2.6001793,
  },
  {
    id: "the-courtrooms",
    category: "university",
    name: "The Courtrooms",
    type: "Postgraduate studio",
    area: "BS1 2AF",
    walk: "约 14 分钟",
    walkMinutes: 14,
    price: "£332.50/w, 51 周, 总 £16,957.50",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/the-courtrooms/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Rupert Street, Bristol BS1 2AF",
    note: "位置和价格都不错，更 city-centre；噪音和街区感需要接受。",
    priority: 4,
    tags: ["官方", "PG", "市中心"],
    lat: 51.4563671,
    lng: -2.5954633,
  },
  {
    id: "manor-hall",
    category: "university",
    name: "Manor Hall",
    type: "Studio",
    area: "BS8 1BU",
    walk: "约 15 分钟",
    walkMinutes: 15,
    price: "Studio £285.46/w",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/manor/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Lower Clifton Hill, Bristol BS8 1BU",
    note: "Clifton 位置好、价格友好；这里只保留 single 可申请的 studio 线索，其他非单人房型不作为推荐。",
    priority: 3,
    tags: ["官方", "Clifton", "低价", "single"],
    lat: 51.4544677,
    lng: -2.6119654,
  },
  {
    id: "clifton-hill-house",
    category: "university",
    name: "Clifton Hill House",
    type: "1-bed flat",
    area: "BS8 1BX",
    walk: "约 15 分钟",
    walkMinutes: 15,
    price: "£264.81/w, 38 周, 总 £10,062.78",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/clifton-hill/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Lower Clifton Hill, Bristol BS8 1BX",
    note: "Clifton 安静、官方且便宜；但主要是 catered residence，1-bed flat 面向 UG 且只有 3 间。",
    priority: 3,
    tags: ["官方", "Clifton", "便宜", "稀缺"],
    lat: 51.4534513,
    lng: -2.6132427,
  },
  {
    id: "winkworth-house",
    category: "university",
    name: "Winkworth House",
    type: "Studio / 1-bed flat",
    area: "BS1 5UU",
    walk: "约 20 分钟",
    walkMinutes: 20,
    price: "Studio £285.46/w; 1-bed £264.81/w",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/winkworth-house/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "5 St Georges Road, Bristol BS1 5UU",
    note: "官方、Harbourside 住宅感更强；到 Wills 正好卡 20 分钟，且 studio / 1-bed 数量很少。",
    priority: 3,
    tags: ["官方", "Harbourside", "20 分钟边界"],
    borderline: true,
    lat: 51.451139,
    lng: -2.604757,
  },
  {
    id: "richmond-terrace",
    category: "university",
    name: "Richmond Terrace",
    type: "Studio",
    area: "BS8 1AD",
    walk: "约 12-15 分钟",
    walkMinutes: 14,
    price: "Studio £285.46/w, 38 周, 总 £10,847.48",
    sourceUrl: officialCostTable,
    sourceLabel: "University cost table",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Richmond Terrace, Bristol BS8 1AD",
    note: "官方成本表列有 studio，Clifton 位置好；但 UG/数量少，申请可得性要单独确认。",
    priority: 3,
    tags: ["官方", "Clifton", "Studio"],
    lat: 51.4552948,
    lng: -2.6132898,
  },
  {
    id: "print-hall",
    category: "university",
    name: "Print Hall",
    type: "Postgraduate studio",
    area: "BS2 0BU",
    walk: "约 23-25 分钟",
    walkMinutes: 24,
    price: "PG studio £299.74/w",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/costs/cost-by-residence/",
    sourceLabel: "University cost table",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "Print Hall, 1 Temple Way, Bristol BS2 0BU",
    note: "官方 PG studio 数量相对多、价格好；其他非单人房型已排除。去 Wills 超过 20 分钟，作为边界备选。",
    priority: 3,
    tags: ["官方", "PG", "single", "边界备选"],
    borderline: true,
    lat: 51.454979,
    lng: -2.5829766,
  },
  {
    id: "st-thomas-street",
    category: "university",
    name: "St Thomas Street",
    type: "Postgraduate studio",
    area: "BS1 6JS",
    walk: "约 22-25 分钟",
    walkMinutes: 23,
    price: "£318.50/w, 51 周, 总 £16,243.50",
    sourceUrl: "https://www.bristol.ac.uk/accommodation/about/residences/st-thomas-street/",
    sourceLabel: "University of Bristol",
    sourceStatus: "verified",
    sourceGroup: "University official",
    origin: "21 St Thomas Street, Bristol BS1 6JS",
    note: "高端 PG studio，设施强；Redcliffe 到 Wills 走路略超 20 分钟，适合能接受通勤的人。",
    priority: 3,
    tags: ["官方", "PG", "边界备选"],
    borderline: true,
    lat: 51.4511079,
    lng: -2.5881408,
  },
  {
    id: "college-house",
    category: "pbsa",
    name: "College House",
    type: "Studios, 偏 PG 友好",
    area: "BS1 5SP",
    walk: "约 5-8 分钟",
    walkMinutes: 7,
    price: "2026/27 from £386/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/college-house",
    sourceLabel: "Hello Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "32-36 College Green, Bristol BS1 5SP",
    note: "安静、独立、全包、近学校，适合想省心的 LLM；预算会高一些。",
    priority: 5,
    tags: ["全包", "PG 友好", "近学校"],
    topPick: true,
    lat: 51.4526709,
    lng: -2.599745,
  },
  {
    id: "st-marys",
    category: "pbsa",
    name: "St Mary's",
    type: "Studios / 1-bed / 2-bed apartments",
    area: "BS8 1JU",
    walk: "约 9 分钟",
    walkMinutes: 9,
    price: "官网实时 View prices",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/st-marys",
    sourceLabel: "Hello Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Upper Byron Place, Bristol BS8 1JU",
    note: "Clifton Triangle 地段非常好，官方页面确认 studios、1/2-bed apartments 和 all-inclusive bills。",
    priority: 5,
    tags: ["Clifton", "全包", "高预算"],
    topPick: true,
    lat: 51.454985,
    lng: -2.6072213,
  },
  {
    id: "holly-court",
    category: "pbsa",
    name: "Holly Court",
    type: "Studios / 1-bed apartments",
    area: "BS2 8DQ",
    walk: "约 7-10 分钟",
    walkMinutes: 9,
    price: "官网实时查",
    sourceUrl: "https://www.crm-students.com/bristol/holly-court",
    sourceLabel: "CRM Students",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Holly Court, High Kingsdown, Bristol BS2 8DQ",
    note: "官方 PBSA list 点名，CRM 页面写大 studio 和 4 间 1-bed；位置在 High Kingsdown，非常靠学校。",
    priority: 5,
    tags: ["全包", "近学校", "1B1B"],
    topPick: true,
    lat: 51.4614251,
    lng: -2.6021158,
  },
  {
    id: "quarter-house",
    category: "pbsa",
    name: "The Quarter House",
    type: "Studios",
    area: "BS1 3NX",
    walk: "约 14-20 分钟",
    walkMinutes: 18,
    price: "Studio £340-405/w",
    sourceUrl: "https://prestigestudentliving.com/student-accommodation/bristol/the-quarter-house",
    sourceLabel: "Prestige Student Living",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "17 Marlborough Street, Bristol BS1 3NX",
    note: "新、设施强、价格相对合理；No Place / No Visa, No Pay 对国际学生友好。",
    priority: 5,
    tags: ["新", "No Visa No Pay", "设施强"],
    topPick: true,
    lat: 51.4596509,
    lng: -2.5919,
  },
  {
    id: "vita-zed-alley",
    category: "pbsa",
    name: "Vita Student Zed Alley",
    type: "Studios",
    area: "BS1 4TT",
    walk: "约 10 分钟",
    walkMinutes: 10,
    price: "官网实时查",
    sourceUrl: "https://www.vitastudent.com/en/cities/bristol/zed-alley/",
    sourceLabel: "Vita Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "35 Colston Avenue, Bristol BS1 4TT",
    note: "Vita 官方写全 studio、Colston Avenue、市中心、到 University of Bristol 步行约 10 分钟；服务配置很强。",
    priority: 5,
    tags: ["全包", "市中心", "设施强"],
    lat: 51.4554749,
    lng: -2.5967425,
  },
  {
    id: "the-colston",
    category: "pbsa",
    name: "The Colston",
    type: "Studios / shared flats",
    area: "BS1 4ST",
    walk: "约 10-12 分钟",
    walkMinutes: 11,
    price: "官网实时查",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/the-colston",
    sourceLabel: "Homes for Students",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "8-10 Colston Avenue, Bristol BS1 4ST",
    note: "Colston Avenue 位置优秀，官网有 studio options；比 Zed Alley 更像普通 PBSA。",
    priority: 4,
    tags: ["市中心", "Studio"],
    lat: 51.454047,
    lng: -2.5965147,
  },
  {
    id: "stonebridge-house",
    category: "pbsa",
    name: "Stonebridge House",
    type: "Studios",
    area: "BS1 4TN",
    walk: "约 10-12 分钟",
    walkMinutes: 11,
    price: "from £279/w",
    sourceUrl: "https://almerostudent.com/properties/bristol/stonebridge-house/",
    sourceLabel: "Almero Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Stonebridge House, Colston Avenue, Bristol BS1 4TN",
    note: "Almero 官方 Bristol 项目之一，Colston Avenue，studio 选择；需核对具体房型和合同。",
    priority: 4,
    tags: ["市中心", "Studio"],
    lat: 51.4556948,
    lng: -2.5965487,
  },
  {
    id: "market-quarter",
    category: "pbsa",
    name: "Market Quarter Studios",
    type: "Studios",
    area: "BS1 1BT",
    walk: "约 12-15 分钟",
    walkMinutes: 14,
    price: "2026/27 from £338/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/market-quarter",
    sourceLabel: "Hello Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "13-21 Baldwin Street, Bristol BS1 1BT",
    note: "市中心 studio，生活方便，全包；Baldwin Street 周边晚上较热闹。",
    priority: 4,
    tags: ["市中心", "全包"],
    lat: 51.4536072,
    lng: -2.5954956,
  },
  {
    id: "college-green",
    category: "pbsa",
    name: "College Green",
    type: "Studios / shared apartments",
    area: "BS1 5SH",
    walk: "约 7-10 分钟",
    walkMinutes: 8,
    price: "from £293/w",
    sourceUrl: "https://www.hellostudent.co.uk/student-accommodation/bristol/college-green",
    sourceLabel: "Hello Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "39-43 College Green, Bristol BS1 5SH",
    note: "离 Wills 很近，价格可能比 College House / St Mary's 更友好。",
    priority: 4,
    tags: ["近学校", "预算友好"],
    lat: 51.4525058,
    lng: -2.5989593,
  },
  {
    id: "iq-bristol",
    category: "pbsa",
    name: "iQ Bristol",
    type: "Studios / ensuite",
    area: "BS1 3EQ",
    walk: "约 15-20 分钟",
    walkMinutes: 18,
    price: "from £315/w, studio 需实时查",
    sourceUrl: "https://www.iqstudentaccommodation.com/bristol/iq-bristol",
    sourceLabel: "iQ Student Accommodation",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Marlborough Street, Bristol BS1 3EQ",
    note: "国际学生流程成熟；guarantor、No Visa No Pay 等条款需以官网实时房型为准。",
    priority: 4,
    tags: ["国际学生", "市中心"],
    lat: 51.4593759,
    lng: -2.5921699,
  },
  {
    id: "new-bridewell",
    category: "pbsa",
    name: "New Bridewell",
    type: "Studios",
    area: "BS1 2BA",
    walk: "约 10-15 分钟",
    walkMinutes: 13,
    price: "Bronze £390/w, higher tiers around £460/w",
    sourceUrl: "https://www.thisisfresh.com/bristol/new-bridewell",
    sourceLabel: "Fresh",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Nelson Street, Bristol BS1 2BA",
    note: "Fresh 系列，位置近，设施稳；市中心噪音和治安体感要看房间朝向。",
    priority: 4,
    tags: ["市中心", "高预算"],
    lat: 51.4568662,
    lng: -2.5939235,
  },
  {
    id: "tower-bristol",
    category: "pbsa",
    name: "Tower Bristol",
    type: "Studios, 部分可 dual occupancy",
    area: "BS1 2QJ",
    walk: "约 10-15 分钟",
    walkMinutes: 13,
    price: "Bronze Studio £360/w, Platinum £421/w",
    sourceUrl: "https://www.collegiate-ac.com/uk-student-accommodation/bristol/tower/",
    sourceLabel: "Collegiate",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Rupert Street, Bristol BS1 2QJ",
    note: "性价比不错；部分房型可能 non-opening windows，必须问通风和朝向。",
    priority: 4,
    tags: ["市中心", "需问通风"],
    lat: 51.4570612,
    lng: -2.5948932,
  },
  {
    id: "st-lawrence-house",
    category: "pbsa",
    name: "St Lawrence House",
    type: "Studios",
    area: "BS1 2HF",
    walk: "约 15-18 分钟",
    walkMinutes: 17,
    price: "£399-465/w",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/st-lawrence-house",
    sourceLabel: "Homes for Students",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "29-31 Broad Street, Bristol BS1 2HF",
    note: "部分 studio 带洗烘机是加分项；Broad Street 去学校不远但夜间城市感强。",
    priority: 4,
    tags: ["市中心", "带洗烘"],
    lat: 51.4556154,
    lng: -2.5952115,
  },
  {
    id: "studio-58",
    category: "pbsa",
    name: "Studio 58",
    type: "Studios",
    area: "BS2 8AL",
    walk: "约 15-18 分钟",
    walkMinutes: 17,
    price: "官网实时查",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/studio-58",
    sourceLabel: "Homes for Students",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Studio 58, Dighton Street, Bristol BS2 8AL",
    note: "自带 kitchenette / bathroom 的 studio，Dighton Street 位置接近 20 分钟内；注意和 King Square 相邻但不是同一项目。",
    priority: 4,
    tags: ["Studio", "市中心"],
    lat: 51.4605995,
    lng: -2.5929258,
  },
  {
    id: "king-square-studios",
    category: "pbsa",
    name: "King Square Studios",
    type: "Studios / 1-bed apartment",
    area: "BS2 8AU",
    walk: "约 16-20 分钟",
    walkMinutes: 19,
    price: "Studio from £295-299/w; 1-bed from £475/w",
    sourceUrl: "https://wearehomesforstudents.com/student-accommodation/bristol/king-square-studios",
    sourceLabel: "Homes for Students",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "4 Dighton Street, Bristol BS2 8AU",
    note: "价格相对低，但接近 20 分钟边界；适合预算敏感又想独立居住的人。",
    priority: 3,
    tags: ["预算友好", "20 分钟边界"],
    borderline: true,
    lat: 51.4611129,
    lng: -2.5925594,
  },
  {
    id: "hotwells-house",
    category: "pbsa",
    name: "Hotwells House",
    type: "Studios / ensuite",
    area: "Hotwells",
    walk: "约 22-25 分钟",
    walkMinutes: 24,
    price: "官网实时查",
    sourceUrl: "https://www.dwellstudent.com/en-gb/bristol/hotwells-house/about-property",
    sourceLabel: "Dwell Student",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Hotwells House, Bristol",
    note: "Dwell Bristol 项目，Hotwells 生活感不错；到 Wills 已经略超过 20 分钟，作为边界备选。",
    priority: 3,
    tags: ["边界备选", "Hotwells"],
    borderline: true,
    lat: 51.4501786,
    lng: -2.617001,
  },
  {
    id: "zinc-quarter",
    category: "pbsa",
    name: "Zinc Quarter",
    type: "Studio rooms",
    area: "BS2 0NU",
    walk: "约 30 分钟",
    walkMinutes: 30,
    price: "Studio from £359/w, all bills",
    sourceUrl: "https://www.studentroost.co.uk/locations/bristol/zinc-quarter",
    sourceLabel: "Student Roost",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "3 Unity Street, Bristol BS2 0NU",
    note: "Student Roost 官方写 studio + all bills；到 UoB main campus 约 30 分钟，除非特别喜欢新楼，否则不是首选。",
    priority: 3,
    tags: ["边界备选", "全包"],
    borderline: true,
    lat: 51.4533752,
    lng: -2.6007979,
  },
  {
    id: "brigg-point",
    category: "pbsa",
    name: "Brigg Point",
    type: "Studios, 2026/27 currently unavailable",
    area: "BS2 0SF",
    walk: "约 30 分钟",
    walkMinutes: 30,
    price: "Studios unavailable; ensuites from £229/w",
    sourceUrl: "https://apartostudent.com/locations/bristol/brigg-point",
    sourceLabel: "aparto",
    sourceStatus: "provider",
    sourceGroup: "PBSA provider",
    origin: "Gas Lane, Bristol BS2 0SF",
    note: "aparto 官方有 studio 类型但当前显示 unavailable；位置偏东，到 Wills 明显超 20 分钟。",
    priority: 3,
    tags: ["边界备选", "需候补"],
    borderline: true,
    lat: 51.4508089,
    lng: -2.5749134,
  },
  {
    id: "queens-road-44a",
    category: "su",
    name: "44a Queens Road",
    type: "Mezzanine studio",
    area: "BS8 1FG",
    walk: "约 2-5 分钟",
    walkMinutes: 3,
    price: "£1,500 pcm, all bills",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/3157-44a-queens-road-clifton-bristol",
    sourceLabel: "Bristol SU Lettings",
    sourceStatus: "provider",
    sourceGroup: "Bristol SU Lettings",
    origin: "44a Queens Road, Clifton, Bristol BS8 1FG",
    note: "离法学院极近，all bills + super-fast Wi-Fi；贵，但地段基本无敌。",
    priority: 5,
    tags: ["SU", "全包", "最近"],
    topPick: true,
    lat: 51.4566,
    lng: -2.6053,
  },
  {
    id: "park-street-1bed",
    category: "su",
    name: "Park Street 1-bed",
    type: "1-bed student flat",
    area: "BS1",
    walk: "约 5 分钟",
    walkMinutes: 5,
    price: "£440/w, bills/Wi-Fi/insurance included",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/3026-park-street-bristol",
    sourceLabel: "Bristol SU Lettings",
    sourceStatus: "provider",
    sourceGroup: "Bristol SU Lettings",
    origin: "Park Street, Bristol",
    note: "真正 1B1B，位置近、学生合同、全包；Park Street 晚上可能吵。",
    priority: 5,
    tags: ["SU", "1B1B", "全包"],
    topPick: true,
    lat: 51.4542763,
    lng: -2.6024851,
  },
  {
    id: "manor-house-park-lane",
    category: "su",
    name: "The Manor House, Park Lane",
    type: "1-bed ensuite student flat",
    area: "BS1/BS8",
    walk: "约 5-8 分钟",
    walkMinutes: 7,
    price: "£560/w, all bills",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/370-the-manor-house-park-lane-bristol",
    sourceLabel: "Bristol SU Lettings",
    sourceStatus: "provider",
    sourceGroup: "Bristol SU Lettings",
    origin: "The Manor House, Park Lane, Bristol",
    note: "很高配、在 UoB precinct，适合预算高的人。",
    priority: 5,
    tags: ["SU", "高配", "高预算"],
    lat: 51.4548,
    lng: -2.6065,
  },
  {
    id: "park-street-studio",
    category: "su",
    name: "Park Street studio",
    type: "Studio",
    area: "BS1 5JG",
    walk: "约 5 分钟",
    walkMinutes: 5,
    price: "£305/w, bills/Wi-Fi included",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/2995-park-street-bristol",
    sourceLabel: "Bristol SU Lettings",
    sourceStatus: "provider",
    sourceGroup: "Bristol SU Lettings",
    origin: "34 Park Street, Bristol BS1 5JG",
    note: "性价比很高，适合单人 LLM；重点看面积、采光和噪音。",
    priority: 4,
    tags: ["SU", "预算友好", "全包"],
    lat: 51.4545,
    lng: -2.6027,
  },
  {
    id: "park-row",
    category: "su",
    name: "Park Row",
    type: "1-bed flat",
    area: "BS1",
    walk: "约 5-8 分钟",
    walkMinutes: 7,
    price: "£1,300 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let/property/2862-park-row-bristol",
    sourceLabel: "Bristol SU Lettings",
    sourceStatus: "provider",
    sourceGroup: "Bristol SU Lettings",
    origin: "Park Row, Bristol",
    note: "更像正常住家的 1B1B；2026/27 可租情况需邮件确认。",
    priority: 4,
    tags: ["SU", "1B1B", "需确认"],
    lat: 51.4554406,
    lng: -2.6006198,
  },
  {
    id: "dover-place",
    category: "su",
    name: "Dover Place",
    type: "1-bed flat",
    area: "Clifton / Triangle",
    walk: "约 3-6 分钟",
    walkMinutes: 5,
    price: "£1,350 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/search-results?start=72",
    sourceLabel: "Bristol SU search",
    sourceStatus: "search",
    sourceGroup: "Bristol SU Lettings",
    origin: "Dover Place, Bristol",
    note: "位置在 SU / Clifton Triangle 旁，适合研究生；bills 是否 included 要确认。",
    priority: 4,
    tags: ["SU", "Clifton", "1B1B"],
    lat: 51.455524,
    lng: -2.6108772,
  },
  {
    id: "cotham-road-south",
    category: "su",
    name: "Cotham Road South",
    type: "Studio",
    area: "BS6/BS8",
    walk: "约 5-10 分钟",
    walkMinutes: 9,
    price: "£1,150 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/search-results?start=72",
    sourceLabel: "Bristol SU search",
    sourceStatus: "search",
    sourceGroup: "Bristol SU Lettings",
    origin: "Cotham Road South, Bristol",
    note: "私人小院 studio，位置好，价格比 PBSA 温和；bills 要确认。",
    priority: 4,
    tags: ["SU", "预算友好", "需问 bills"],
    lat: 51.4628031,
    lng: -2.5976902,
  },
  {
    id: "whiteladies-road",
    category: "su",
    name: "Whiteladies Road",
    type: "Studio",
    area: "BS8",
    walk: "约 10-15 分钟",
    walkMinutes: 14,
    price: "£1,500 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let?start=72",
    sourceLabel: "Bristol SU search",
    sourceStatus: "search",
    sourceGroup: "Bristol SU Lettings",
    origin: "Whiteladies Road, Bristol BS8",
    note: "生活方便，Clifton / Redland 氛围好；价格偏高。",
    priority: 3,
    tags: ["SU", "Clifton", "高预算"],
    lat: 51.4647619,
    lng: -2.6098274,
  },
  {
    id: "st-stephens-street",
    category: "su",
    name: "14 St Stephens Street",
    type: "Studio",
    area: "BS1",
    walk: "约 12-17 分钟",
    walkMinutes: 15,
    price: "£1,150 pcm",
    sourceUrl: "https://www.bristolsulettings.co.uk/properties-to-let?start=84",
    sourceLabel: "Bristol SU search",
    sourceStatus: "search",
    sourceGroup: "Bristol SU Lettings",
    origin: "14 St Stephens Street, Bristol",
    note: "市中心、价格还行；晚上环境不如 Clifton 安静。",
    priority: 3,
    tags: ["SU", "市中心", "预算友好"],
    lat: 51.4532,
    lng: -2.5944,
  },
  {
    id: "private-queens-road",
    category: "private",
    name: "Queens Road, Clifton",
    type: "Studio / 1-bed student studio",
    area: "BS8",
    walk: "约 3-5 分钟",
    walkMinutes: 4,
    price: "约 £1,250 pcm / £288 pw",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/studio-flats.html",
    sourceLabel: "Rightmove BS8 studios",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Queens Road, Clifton, Bristol BS8",
    note: "对 Law School 最方便；主路/酒吧噪音和房间大小要重点看。",
    priority: 5,
    tags: ["最近", "社会房源", "预算友好"],
    verifyLive: true,
    lat: 51.4562,
    lng: -2.6048,
  },
  {
    id: "berkeley-square",
    category: "private",
    name: "Berkeley Square",
    type: "Studio / 1-bed",
    area: "BS8",
    walk: "约 3-6 分钟",
    walkMinutes: 5,
    price: "Studio £1,175 pcm; 1-bed £1,495 pcm",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/studio-flats.html",
    sourceLabel: "Rightmove BS8 studios",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Berkeley Square, Bristol",
    note: "位置顶级，靠近 Wills 和 Park Street；社会房合同细节要更仔细。",
    priority: 4,
    tags: ["Clifton", "近学校"],
    verifyLive: true,
    lat: 51.4551954,
    lng: -2.6057509,
  },
  {
    id: "jacobs-wells-road",
    category: "private",
    name: "Jacobs Wells Road",
    type: "Student-only studios",
    area: "BS8",
    walk: "约 8-12 分钟",
    walkMinutes: 10,
    price: "£1,265 pcm / £292 pw, all bills",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/studio-flats.html",
    sourceLabel: "Rightmove student studios",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Jacobs Wells Road, Bristol BS8",
    note: "到 Clifton Triangle 很近，全包省心；注意坡度、采光和隔音。",
    priority: 4,
    tags: ["全包", "学生房", "近学校"],
    verifyLive: true,
    lat: 51.452831,
    lng: -2.6097464,
  },
  {
    id: "meridian-place",
    category: "private",
    name: "Meridian Place",
    type: "1-bed flat",
    area: "Clifton BS8",
    walk: "约 8-12 分钟",
    walkMinutes: 10,
    price: "£1,400 pcm",
    sourceUrl: "https://www.zoopla.co.uk/to-rent/flats/bristol/clifton/queens-road/",
    sourceLabel: "Zoopla Queens Road / Meridian",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Meridian Place, Clifton, Bristol BS8",
    note: "Clifton 好位置，社会房源里比较稳；问家具、bills、guarantor。",
    priority: 4,
    tags: ["Clifton", "1B1B"],
    verifyLive: true,
    lat: 51.4561554,
    lng: -2.6106542,
  },
  {
    id: "baldwin-street",
    category: "private",
    name: "Baldwin Street",
    type: "Studio",
    area: "BS1",
    walk: "约 12-15 分钟",
    walkMinutes: 14,
    price: "£1,350-1,475 pcm",
    sourceUrl: "https://www.bristolpropertycentre.co.uk/property-details/33483065/city-of-bristol/bristol/baldwin-chambers",
    sourceLabel: "Bristol Property Centre",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Baldwin Street, Bristol BS1",
    note: "市中心生活方便，价格中等；晚上热闹，适合能接受 city-centre 的人。",
    priority: 4,
    tags: ["市中心", "Studio"],
    verifyLive: true,
    lat: 51.4535145,
    lng: -2.5935229,
  },
  {
    id: "queen-square",
    category: "private",
    name: "Queen Square",
    type: "Student studios",
    area: "BS1",
    walk: "约 17-20 分钟",
    walkMinutes: 20,
    price: "£1,170-1,404 pcm",
    sourceUrl: "https://www.zoopla.co.uk/to-rent/flats/bristol/queen-square/",
    sourceLabel: "Zoopla Queen Square",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Queen Square, Bristol BS1",
    note: "位置漂亮、靠近 Harbourside；到 Wills 卡 20 分钟边界。",
    priority: 3,
    tags: ["Harbourside", "20 分钟边界"],
    verifyLive: true,
    borderline: true,
    lat: 51.4506099,
    lng: -2.5958078,
  },
  {
    id: "canynge-square",
    category: "private",
    name: "Canynge Square",
    type: "1-bed flat",
    area: "Clifton BS8",
    walk: "约 16-20 分钟",
    walkMinutes: 19,
    price: "£1,300 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Canynge Square, Clifton, Bristol BS8",
    note: "Clifton Village 生活品质高；去 Wills 有坡，时间接近 20 分钟。",
    priority: 3,
    tags: ["Clifton Village", "1B1B"],
    verifyLive: true,
    borderline: true,
    lat: 51.4554,
    lng: -2.6205,
  },
  {
    id: "clifton-park-road",
    category: "private",
    name: "Clifton Park Road",
    type: "1-bed flat",
    area: "BS8",
    walk: "约 12-18 分钟",
    walkMinutes: 17,
    price: "£1,600 pcm",
    sourceUrl: "https://www.rightmove.co.uk/student-accommodation/BS8/1-bed-flats.html",
    sourceLabel: "Rightmove BS8 1-bed",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Clifton Park Road, Bristol BS8",
    note: "居住感强，位置好；价格偏高。",
    priority: 3,
    tags: ["Clifton", "高预算"],
    verifyLive: true,
    lat: 51.4592676,
    lng: -2.6208614,
  },
  {
    id: "kings-parade-avenue",
    category: "private",
    name: "Kings Parade Avenue",
    type: "Studio",
    area: "Whiteladies 附近",
    walk: "约 15-20 分钟",
    walkMinutes: 19,
    price: "约 £950 pcm",
    sourceUrl: "https://www.rightmove.co.uk/property-to-rent/BS8/flats.html",
    sourceLabel: "Rightmove BS8 flats",
    sourceStatus: "volatile",
    sourceGroup: "Private market",
    origin: "Kings Parade Avenue, Bristol BS8",
    note: "价格低，但要重点检查面积、采光、潮湿、取暖和 bills。",
    priority: 3,
    tags: ["低价", "需仔细看房"],
    verifyLive: true,
    borderline: true,
    lat: 51.467234,
    lng: -2.6130334,
  },
];

export const sourceAudit: SourceAudit[] = [
  {
    group: "University official",
    included: [
      "Marlborough House",
      "Orchard Heights",
      "The Courtrooms",
      "Manor Hall studio only",
      "Clifton Hill House",
      "Winkworth House",
      "Richmond Terrace",
    ],
    borderline: ["Print Hall", "St Thomas Street"],
    excluded: [
      "Campus Houses and University family/couples accommodation: excluded because this guide is for an unaccompanied single LLM applicant",
      "Official 1-bed couple/family variants inside Print Hall / Manor Hall / Campus Houses: excluded from recommendations",
      "Stoke Bishop options such as Wills Hall, Churchill, Hiatt Baker, Badock, Durdham: outside the 20-minute walking target",
      "Langford and other non-city options: too far for Wills / Law School",
      "Shared en-suite or single-room only entries: outside Studio + 1B1B scope",
    ],
  },
  {
    group: "PBSA providers",
    included: [
      "Hello Student College House, St Mary's, College Green, Market Quarter",
      "CRM Holly Court",
      "Prestige The Quarter House",
      "Vita Student Zed Alley",
      "Homes for Students The Colston, Studio 58, St Lawrence House, King Square Studios",
      "iQ Bristol, Fresh New Bridewell, Collegiate Tower, Almero Stonebridge House",
    ],
    borderline: ["Dwell Hotwells House", "Student Roost Zinc Quarter", "aparto Brigg Point"],
    excluded: [
      "PBSA provider pages without a close Bristol studio/1-bed candidate or without clear 2026 availability",
      "Projects aimed mainly at UWE / Temple Quarter when Wills walking time is around 30 minutes or more",
    ],
  },
  {
    group: "Bristol SU Lettings",
    included: [
      "44a Queens Road",
      "Park Street 1-bed",
      "The Manor House Park Lane",
      "Park Street studio",
      "Park Row",
      "Dover Place",
      "Cotham Road South",
      "Whiteladies Road",
      "14 St Stephens Street",
    ],
    borderline: [],
    excluded: ["Shared houses and non-studio rooms", "Listings without public detail pages are linked through search results"],
  },
  {
    group: "Private market",
    included: [
      "Queens Road",
      "Berkeley Square",
      "Jacobs Wells Road",
      "Meridian Place",
      "Baldwin Street",
      "Queen Square",
      "Canynge Square",
      "Clifton Park Road",
      "Kings Parade Avenue",
    ],
    borderline: ["Queen Square", "Canynge Square", "Kings Parade Avenue"],
    excluded: [
      "Rightmove / Zoopla / OpenRent results outside BS1/BS8 or without student/studio/1-bed fit",
      "Listings that are clearly over 20 minutes without a strong international-student reason to keep",
    ],
  },
];
